Repository AY2425S1-CS2103T-W10-3/tp, pull requests merged in 2024-10, with the labels that each got.

#26 Update AboutUs.md
  docs/AboutUs.md
Labels: type.Task

#28 Update DeveloperGuide.md with adding client feature
  docs/DeveloperGuide.md
Labels: type.Task

#30 Update DG with User stories and more
  docs/DeveloperGuide.md
Labels: type.Task

#33 Update DG for delete contact
  docs/DeveloperGuide.md
Labels: priority.High, type.Task

#36 Update DeveloperGuide.md Use Case for edit client details feature
  docs/DeveloperGuide.md
Labels: type.Task

#38 Update DG with new use cases
  docs/DeveloperGuide.md
Labels: type.Task

#40 Configure config.yaml file, update README.md and modify UI interface
  README.md
  docs/_config.yml
  docs/images/Ui.png
Labels: type.Task

#42 Update DG with more NFR and glossary
  docs/DeveloperGuide.md
Labels: type.Task

#50 Add sort command
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
Labels: priority.High, type.Task

#48 Update delete command to take name
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: priority.High, type.Task

#52 Add new details for Person
  src/main/java/seedu/address/model/person/Appointment.java
  src/main/java/seedu/address/model/person/Birthday.java
  src/main/java/seedu/address/model/person/Payment.java
  src/main/java/seedu/address/model/person/Policy.java
  src/test/java/seedu/address/model/person/AppointmentTest.java
  src/test/java/seedu/address/model/person/BirthdayTest.java
  src/test/java/seedu/address/model/person/PaymentTest.java
  src/test/java/seedu/address/model/person/PolicyTest.java
Labels: priority.High, type.Task

#54 Edit AddCommand to handle birthday and appointment
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Appointment.java
  src/main/java/seedu/address/model/person/Birthday.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Enhancement

#56 Update edit command with policy
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
Labels: priority.High, type.Task

#58 Delete command confirmation
  build.gradle
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
Labels: priority.Medium, type.Enhancement

#64 Branch search birthday appointment
  1
  README.md
  build.gradle
  docs/AboutUs.md
  docs/DeveloperGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/SearchAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/SearchBirthdayCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SearchCommandParser.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/SearchAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/SearchBirthdayCommandTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Task

#66 Update User Guide
  docs/UserGuide.md
Labels: priority.Medium, type.Task

#68 Update User Guide for Edit Command
  docs/UserGuide.md
Labels: priority.Medium, type.Task

#70 Modify UG and add UI screenshots
  docs/UserGuide.md
  docs/images/assignpolicyUI.png
  docs/images/deleteUI.png
  docs/images/editUI.png
  docs/images/searchapptUI.png
  docs/images/searchbirthdayUI.png
  docs/images/sortUI.png
  docs/images/sortapptUI.png
  docs/images/sortnameUI.png
Labels: type.Task

#72 Delete policy
  build.gradle
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High, type.Task

#74 Update Sort Command
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/person/Payment.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Policy.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
Labels: priority.High, type.Task

#78 Save policies to json
  src/main/java/seedu/address/model/person/Payment.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Policy.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedPolicies.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: priority.Medium, type.Enhancement

#80 Fix edit command allowing duplicate policy names
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: priority.High, type.Bug

#82 Branch search policy feature
  src/main/java/seedu/address/logic/commands/SearchPolicyCommand.java
  src/main/java/seedu/address/logic/parser/SearchCommandParser.java
  src/test/java/seedu/address/logic/commands/SearchPolicyCommandTest.java
  src/test/java/seedu/address/logic/parser/SearchCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High, type.Task

#85 Branch search birthday upgrade
  src/main/java/seedu/address/logic/commands/SearchBirthdayCommand.java
  src/main/java/seedu/address/logic/parser/SearchCommandParser.java
  src/test/java/seedu/address/logic/commands/SearchBirthdayCommandTest.java
Labels: priority.Medium, type.Enhancement

#88 Branch search appointment update
  src/main/java/seedu/address/logic/commands/SearchAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/SearchCommandParser.java
  src/test/java/seedu/address/logic/commands/SearchAppointmentCommandTest.java
Labels: priority.Medium, type.Enhancement

#87 Add AddSequenceDiagram
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddSequenceDiagram.puml
Labels: priority.Medium, type.Task

#96 Update UML Diagram
  docs/diagrams/SortSequenceDiagram.puml
Labels: priority.High, type.Task

#76 Update DG and UML diagram
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/images/DeleteSequenceDiagram.png
Labels: priority.High, type.Task

#92 Branch update uml diagram
  docs/diagrams/SearchAppointmentSequenceDiagram.puml
  docs/diagrams/SearchBirthdaySequenceDiagram.puml
  docs/diagrams/SearchPolicySequenceDiagram.puml
Labels: priority.High, type.Task

#100 Add EditNameSequenceDiagram
  docs/diagrams/EditNameSequenceDiagram.puml
Labels: priority.Medium, type.Task

#99 Fix Policy Format Bug
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AssignPolicyCommand.java
  src/main/java/seedu/address/logic/parser/AssignPolicyCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Payment.java
  src/main/java/seedu/address/model/person/Policy.java
  src/test/java/seedu/address/logic/commands/AssignPolicyCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AssignPolicyCommandParserTest.java
Labels: severity.Medium

#94 Add Paid Command
  src/main/java/seedu/address/logic/commands/PaidCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/PaidCommandParser.java
  src/main/java/seedu/address/model/person/Payment.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Policy.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/PaidCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/PaidCommandParserTest.java
  src/test/java/seedu/address/model/person/PaymentTest.java
Labels: priority.High, type.Task

#105 Fixing test cases related to storage
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/commands/PaidCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, severity.High, alpha-bug

#104 Update UG to include screenshots
  docs/UserGuide.md
  docs/images/DeletePersonUndoUI.png
  docs/images/DeletePolicyUI.png
  docs/images/RedoUI.png
  docs/images/UndoUI.png
Labels: type.Task

#107 Improve user guide
  docs/UserGuide.md
  docs/images/searchapptrangeUI.png
  docs/images/searchbirthdayrangeUI.png
  docs/images/searchpolicyUI.png
Labels: type.Task

#112 Fix User Guide Navigability
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Policy.java
Labels: alpha-bug

#116 Updating user guide
  docs/UserGuide.md
  docs/images/paidUI.png
  docs/images/sortpaydateUI.png
Labels: priority.High, type.Task
