Repository AY2425S1-CS2103T-W10-3/tp, pull requests merged in 2024-11, with the labels that each got.

#120 Improve code quality
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/SearchAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/SearchBirthdayCommand.java
  src/main/java/seedu/address/logic/commands/SearchPolicyCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/test/java/seedu/address/logic/commands/SearchAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/SearchBirthdayCommandTest.java
  src/test/java/seedu/address/logic/commands/SearchPolicyCommandTest.java
Labels: type.Enhancement

#129 Improve error message handling and improve address handling
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AssignPolicyCommand.java
  src/main/java/seedu/address/logic/parser/AssignPolicyCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Payment.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/Policy.java
  src/main/java/seedu/address/storage/JsonAdaptedPolicies.java
  src/test/java/seedu/address/logic/commands/AssignPolicyCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/PaidCommandTest.java
  src/test/java/seedu/address/logic/commands/SearchPolicyCommandTest.java
  src/test/java/seedu/address/logic/parser/AssignPolicyCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/model/person/PolicyTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High, severity.Medium, type.Bug, alpha-bug

#136 Modify code to fix alpha bugs
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/SearchAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/SearchBirthdayCommand.java
  src/main/java/seedu/address/logic/parser/SearchCommandParser.java
Labels: type.Bug

#144 Fix alpha bugs
  build.gradle
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
Labels: priority.High, type.Task, alpha-bug

#145 Fixing alpha bugs
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/PaidCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/PaidCommandParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Policy.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/PaidCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/PaidCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
Labels: alpha-bug

#146 Improve user guide
  docs/UserGuide.md
  docs/images/DeletePolicyUI.png
  docs/images/GUI.png
  docs/images/RedoUI.png
  docs/images/UndoUI.png
  docs/images/addUI.png
  docs/images/assignpolicyUI.png
  docs/images/deleteUI.png
  docs/images/deletepolicyUI.png
  docs/images/editUI.png
  docs/images/findstevenkurtResult.png
  docs/images/helpMessage.png
  docs/images/paidUI.png
  docs/images/redoUI.png
  docs/images/searchapptUI.png
  docs/images/searchapptrangeUI.png
  docs/images/searchbirthdayUI.png
  docs/images/searchbirthdayrangeUI.png
  docs/images/searchpolicyUI.png
  docs/images/sortapptUI.png
  docs/images/sortbirthdayUI.png
  docs/images/sortnameUI.png
  docs/images/sortpaydateUI.png
  docs/images/undoUI.png
Labels: type.Enhancement

#150 update UG and readme
  README.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AssignPolicyCommand.java
  src/main/java/seedu/address/logic/parser/AssignPolicyCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AssignPolicyCommandParserTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: priority.Medium

#152 Modify user guide
  docs/UserGuide.md
  docs/_layouts/page.html
  docs/images/agentconnectlogo.png
Labels: type.Enhancement

#151 Improve code quality
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/Ui.png
  docs/index.md
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
Labels: priority.Medium, type.Enhancement

#155 Improve dg manual testing
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High, type.Enhancement

#157 UG and DG Update
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  src/main/java/seedu/address/model/person/Policy.java
Labels: priority.Medium

#159 Add tips and notes to UG
  docs/UserGuide.md
Labels: type.Enhancement

#158 Fix Alpha Bugs
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: priority.Medium, type.Task, alpha-bug

#162 Updating user guide
  docs/UserGuide.md
Labels: type.Enhancement

#161 Enable text wrapping for confirmation dialog
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Enhancement

#163 Branch UG format standardise
  docs/UserGuide.md
  docs/images/deletepolicyUI.png
Labels: type.Enhancement

#169 Modify headers from UG and index.md
  docs/_sass/minima/_base.scss
  docs/index.md
Labels: type.Enhancement

#174 modify formats
  docs/UserGuide.md
Labels: type.Bug

#177 edit DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CommandSummaryActivityDiagram.puml
  docs/images/CommandSummaryActivityDiagram.png
Labels: priority.Medium

#179 Branch validate dates
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Appointment.java
  src/main/java/seedu/address/model/person/Birthday.java
  src/main/java/seedu/address/model/person/Policy.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/SearchAppointmentCommandTest.java
  src/test/java/seedu/address/model/person/AppointmentTest.java
  src/test/java/seedu/address/model/person/BirthdayTest.java
  src/test/java/seedu/address/model/person/PolicyTest.java
Labels: priority.Medium

#178 Verify no duplicate prefixes for Paid and Delete Commands
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/PaidCommandParser.java
Labels: type.Bug

#180 Fix UG
  docs/UserGuide.md
Labels: priority.High

#181 Fix Format Error
  docs/UserGuide.md
Labels: type.Bug

#182 Modify file name
  README.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/index.md
Labels: type.Bug

#256 Branch ped fix
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/AssignPolicyCommandParser.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Birthday.java
  src/main/java/seedu/address/model/person/Payment.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Policy.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AssignPolicyCommandParserTest.java
Labels: type.Bug

#258 Modify DG and UG to fix bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.Medium

#260 Branch modify dg content
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/SearchAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/SearchBirthdayCommand.java
  src/main/java/seedu/address/logic/commands/SearchPolicyCommand.java
  src/main/java/seedu/address/model/person/Appointment.java
  src/main/java/seedu/address/model/person/Birthday.java
  src/main/java/seedu/address/model/person/Policy.java
  src/test/java/seedu/address/logic/commands/SearchAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/SearchBirthdayCommandTest.java
  src/test/java/seedu/address/logic/commands/SearchPolicyCommandTest.java
Labels: priority.Medium

#262 declare code reuse
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AssignPolicyCommand.java
  src/main/java/seedu/address/logic/parser/AssignPolicyCommandParser.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Appointment.java
  src/main/java/seedu/address/model/person/Policy.java
Labels: type.Task

#263 Branch code declaration
  src/main/java/seedu/address/logic/commands/SearchAppointmentCommand.java
  src/main/java/seedu/address/model/person/Appointment.java
  src/main/java/seedu/address/model/person/Birthday.java
Labels: priority.Low

#266 Branch ug layout
  docs/UserGuide.md
Labels: priority.Low

#257 Fixing PE-D bugs
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
Labels: priority.High, severity.Low, type.Bug

#267 Fix ped bugs and Add Code Reuse
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/VersionedAddressBook.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
Labels: type.Enhancement

#171 Updating developer guide
  docs/DeveloperGuide.md
Labels: type.Enhancement

#268 Added more test cases for search features
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/test/java/seedu/address/logic/commands/SearchAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/SearchBirthdayCommandTest.java
  src/test/java/seedu/address/logic/commands/SearchPolicyCommandTest.java
Labels: priority.Low
